{{- if .Values.httpServer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "observatory-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "observatory-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.httpServer.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "observatory-server.selectorLabels" . | nindent 4 }}
{{- end -}}
